import 'package:kanpai/generated/l10n.dart';

class Flavor {
  final Map<String, String> flavorName = {
    "Acid": S.current.acid,
    "Aged": S.current.aged,
    "Dry": S.current.dry,
    "Earthy": S.current.earthy,
    "Floral": S.current.floral,
    "Fragrant": S.current.fragrant,
    "Fruity": S.current.fruity,
    "Fresh": S.current.fresh,
    "Light": S.current.light,
    "Matured": S.current.matured,
    "Mellow": S.current.mellow,
    "Round": S.current.round,
    "Rich": S.current.rich,
    "Refined": S.current.refined,
    "Sweet": S.current.sweet,
    "Soft": S.current.soft,
    "Peach": S.current.peach,
    "Aromatic": S.current.aromatic,
    "Grilled Rice": S.current.grilled_rice,
    "Clear": S.current.clear,
    "Balanced": S.current.balanced,
    "Mineral": S.current.mineral,
    "Long": S.current.long,
    "Melon": S.current.melon,
    "Delicate": S.current.delicate,
    "Caramelized": S.current.caramelized,
    "Ripe Fruit": S.current.ripe_fruit,
    "Banana": S.current.banana,
    "Powerful": S.current.powerful,
    "Woody": S.current.woody,
    "Silky": S.current.silky,
    "Bitterness": S.current.bitterness,
    "Elegant": S.current.elegant,
    "Pepper": S.current.pepper,
    "Tasty": S.current.tasty,
    "Complex": S.current.complex,
    "Sparkling": S.current.sparkling,
    "Off-dry": S.current.off_dry,
    "Pear": S.current.pear,
    "Grape": S.current.grape,
    "Traditional": S.current.traditional,
    "Rice Flavor": S.current.rice_flavor,
    "Racy": S.current.racy,
    "Aniseed": S.current.aniseed,
    "Premium": S.current.premium,
    "Pure": S.current.pure,
    "Dense": S.current.dense,
    "Umami": S.current.umami,
    "Natural": S.current.natural,
    "Creamy": S.current.creamy,
    "Acidulous": S.current.acidulous,
    "Black rice": S.current.black_rice,
    "Expressive": S.current.expressive,
    "Licorice": S.current.licorice,
    "Pineapple": S.current.pineapple,
    "Apple": S.current.apple,
    "Fresh Nuts": S.current.fresh_nuts,
    "Clove": S.current.clove,
    "Subtle": S.current.subtle,
    "Shaded": S.current.shaded,
    "Lemon": S.current.lemon,
    "Citrus": S.current.citrus,
    "Refreshing": S.current.refreshing,
    "Restrained": S.current.restrained,
    "Clean": S.current.clean,
    "Fresh Milk": S.current.fresh_milk,
    "Herbs": S.current.herbs,
    "White Flowers": S.current.white_flowers,
    "Bubblegum": S.current.bubblegum,
    "Lychee": S.current.lychee,
    "Ripe Banana": S.current.ripe_banana,
    "Salty": S.current.salty,
    "Fatty": S.current.fatty,
    "Rancid": S.current.rancid,
    "Rubber": S.current.rubber,
    "Plastic": S.current.plastic,
    "Solvent": S.current.solvent,
    "Papery": S.current.papery,
    "Dusty": S.current.dusty,
    "Musty": S.current.musty,
    "Fungal": S.current.fungal,
    "Burnt": S.current.burnt,
    "Smoky": S.current.smoky,
    "Meaty": S.current.meaty,
    "Roasted": S.current.roasted,
    "Dark": S.current.dark,
    "Rice bran": S.current.rice_bran,
    "Steamed rice": S.current.steamed_rice,
    "Malt": S.current.malt,
    "Vanilla": S.current.vanilla,
    "Resinous": S.current.resinous,
    "Savoury": S.current.savoury,
    "Dried": S.current.dried,
    "Cinnamon": S.current.cinnamon,
    "Bitter": S.current.bitter,
    "Mint": S.current.mint,
    "Basil": S.current.basil,
    "Black tea": S.current.black_tea,
    "Tobacco": S.current.tobacco,
    "Bay leaf": S.current.bay_leaf,
    "Lemongrass": S.current.lemongrass,
    "Hay": S.current.hay,
    "Green leaves": S.current.green_leaves,
    "Green tea": S.current.green_tea,
    "Lily": S.current.lily,
    "Rose": S.current.rose,
    "Lilac": S.current.lilac,
    "Acacia": S.current.acacia,
    "Linden": S.current.linden,
    "Geranium": S.current.geranium,
    "Beeswax": S.current.beeswax,
    "Green apple": S.current.green_apple,
    "Strawberry": S.current.strawberry,
    "Fig": S.current.fig,
    "Orange": S.current.orange,
    "Grapefruit": S.current.grapefruit,
    "Yuzu": S.current.yuzu,
    "Apricot": S.current.apricot,
    "Cherry": S.current.cherry,
    "Plum": S.current.plum,
    "Baked banana": S.current.baked_banana,
    "Full": S.current.full,
    "Medium": S.current.medium,
    "Desert": S.current.desert,
    "Metallic": S.current.metallic,
    "Foaming": S.current.foaming,
    "Tingling": S.current.tingling,
    "Aftertaste": S.current.aftertaste,
    "Mouth coating": S.current.mouth_coating,
    "Smooth": S.current.smooth,
    "Velvety": S.current.velvety,
    "Homogeneous": S.current.homogeneous,
    "Lumpy": S.current.lumpy,
    "Grainy": S.current.grainy,
    "Sharp": S.current.sharp,
    "Alcoholic": S.current.alcoholic,
    "Hot": S.current.hot,
    "Yogurt": S.current.yogurt,
    "Mozzarella": S.current.mozzarella,
    "": "",
  };

  String getFlavorName(String pairing) {
    return flavorName[pairing];
  }
}
